### PR TITLE
[License Rebase Required] Prepend Note Title to body as heading if the note has no Metadata

### PR DESCRIPTION
**Pull request by lucidBrot**
## Connection with issue(s)

Resolve issue #579

Connected to #579

## Testing and Review Notes

* Needs review as to the changes I did to the asserts and `pubspec.lock`. I am not familiar enough with flutter and the codebase to judge whether those should be undone again or not.
* The relevant setting is `Settings > Storage & File Formats > Note Metadata Settings > Enable YAML Header`. When `disabled`, editing and saving a note would lose the note title. When `enabled` it was working. Now, both should be working.
* Are there any alternative settings I am not aware of that would not be compatible with my changes?

## To Do
* Add some tests to ensure this does not happen again. I.e. a test whether the note title after saving and loading again is still present. Both with and without YAML header enabled. I do not know yet how to write such a test and in fact did not even manage to run all of the existing tests.
* Run the existing tests to ensure nothing is broken

### CODE REVIEW

**Comment by vHanda** [comment]
Could you please rebase this on master?

I've explicitly added in the README that contributions by others are under Apache2. This way I don't need to bother with CLAs and can continue releasing this on the ios App Store.

**Comment by lucidBrot** [comment]
I'll try to do that sometime soon. I hope my local project is still around so I can ensure my change is still solid after the rebase onto master.

In case I'd forget and not get to it within reasonable time, you have my permission to simply take my fix and add it yourself (if this statement is enough for you).

**Comment by vHanda** [comment]
@lucidBrot : Don't worry about it. I'm going to merge this and create a pull request with adding your name for the license of that file, and tag you. As long as you approve it, that should be enough.

**Comment by lucidBrot** [comment]
Closing in favor of https://github.com/GitJournal/GitJournal/pull/942 which contains this PR's changes rebased on the latest master, and some additional (speed) improvements.

**Pull request closed without merging**
