### PR TITLE
Fix bug where saving new note can create duplicate files

### PR DESCRIPTION
**Pull request by locofocos**
## Connection with issue(s)

Resolve issue #638

## Testing and Review Notes

Steps to reproduce/test:
* Tap + to create a new note. The editor appears.
* Type in a title and a note body
* Press android's home button.
* Open android's Recents screen. (Swipe up on newer phones, or the square/rectangle nav bar button on older phones)
* Find GitJournal and tap to open it back up.
* Tap the check mark (top left) to save the note.
* Notice that only 1 copy of the note is saved.

Context / what I learned
* This was happening because the note was already being saved to disk when closing the app https://github.com/GitJournal/GitJournal/blob/9a14048bf67c1cbb2eb20d55eb171fc63f587cf3/lib/editors/note_editor.dart#L242 but then it was getting saved again here (with the new filename) https://github.com/GitJournal/GitJournal/blob/9a14048bf67c1cbb2eb20d55eb171fc63f587cf3/lib/editors/note_editor.dart#L522 The call to `repo.addNote(note)` is basically running `git add .`, and it was picking up both copies of the file.
* I am doing IO operations without adding a try/catch. But the code already is running inside a try/catch with a pretty generic catch block, so any possible errors should be handled gracefully here.

## Screenshots or Videos

Image 2022-10-16 at 1 09 32 AM

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers

### CODE REVIEW

**Comment by bjackman** [comment]
I also experienced issue https://github.com/GitJournal/GitJournal/issues/638, including on `master` in a virtual device. Can confirm that this PR fixed it for me too. I first rebased it - the conflict is trivial.

@vHanda it would be great to get this merged!

**Comment by vHanda** [comment]
Thank you for these changes.

Could you please rebase your changes? I've added a clause in the README specifying that all contributions will be in Apache2 license. Would that work for you? I want GitJournal to be released under GPL, but that would remove it from the iOS store, and I don't want to deal with CLAs.

**Comment by locofocos** [comment]
@vHanda I've rebased the changes. Yes, you may license these changes however you wish. Thank you!

**Comment by vHanda** [comment]
Rebased and merged!

https://github.com/GitJournal/GitJournal/commit/536f909bba2dc9299f71f6ae42df6184bfb21634

Thank you.

**Comment by locofocos** [comment]
Thanks for maintaining the project 👍

**Pull request closed without merging**
