### PR TITLE
Fix multiple tags with same prefix parsing #268

### PR DESCRIPTION
**Pull request by bchauvin**
## Connection with issue(s)

Resolve issue #268 

## Testing and Review Notes

Added a unit test.

### CODE REVIEW

**Comment by vHanda** [comment]
Oh. Awesome. Thank you for even providing a fix.

I'll try to setup the CLA bot today.

**Comment by bchauvin** [comment]
Sure! 
If you could give me indications or point me to some documentation on how to run the tests locally, that would help me contribute more ambitious things in the future. 

For this one I tested manually against an online tool, so I would recommend doing a test run just in case I might have caused a regression.

**Comment by bchauvin** [comment]
Just realized that the fix above impacts one of your tests: when writing how#are you #are is detected as a tag, and it seems you didn't want that: I understand because it may cause issues with pasted URLs for instance . 

I'm closing the PR and will try to come back later with a proper fix this time.

**Comment by bchauvin** [comment]
OK so this time I'm back with a more solid suggestion, that makes all test pass and fixes #268 (I added some tests as well).
I'm sorry for the complexity of the regex, makes it hard to read and understand but couldn't simplify it further and keep all tests passing.

**Comment by vHanda** [comment]
Hi. I'm sorry about this taking so long. GitJournal is still not really ready for external contributions as I haven't figured out how to get a CLA signed. It's required as when publishing on the iOS store - [it isn't clear](https://apple.stackexchange.com/questions/6109/is-it-possible-to-have-gpl-software-in-the-mac-app-store) if Apple they will allow AGPL licensed code in the App Store.

I've relicensed the files you've touched under MIT, could you please rebase your changes on top of them and add your name to the respective files, then I can merge this and make a new release.

**Pull request closed without merging**
