### PR TITLE
Image zooming

### LINKED ISSUE #386: Pinch and zoom images
A user has requested the ability to pinch and zoom images.

### LINKED ISSUE #410: Enable Image Zooming
Images that are very small e.g. in Tables:
grafik
May be hard to see on small phone screens. 

They could be shown in a full screen view or as an Overlay, that can be closed by tapping.

Additionaly in this preview they should be zoomable by dragging.

https://pub.dev/packages/photo_view

### PR DESCRIPTION
**Pull request by ModProg**
## Connection with issue(s)

- Fixes #410 
- Fixes #386

## Changes
- [x] Added flutterw for consistent flutter versions between developers
- [x] Image Details for all Images
- [x] Rotate Images
- [ ] Move Disable Transparency Setting somewhere else
- [x] Zooming in Image Details works  
- [x] Show Caption in Image Details
- [x] Moved All Image related things in a sub folder of widgets and split monolithic file
- [x] Add option to restrict image Size

### Opens for all Images
All Images
### Rotate by 90°
Rotate
### Zoom in
Zoomin

### CODE REVIEW

**Comment by vHanda** [comment]
This is so awesome. Let me know when you want me to merge it. I can do it now or after you feel it's done.

**Comment by ModProg** [comment]
Will finish it today, just need to add two settings.

18.03.2021 11:41:06 Vishesh Handa ***@***.***>:

**Comment by ModProg** [comment]
BTW what do you think of prefixing Settings with their scope?
The Settings Class is quite a monolith, so it could help to Name Settings of Display/Image like this `display_image_maxZoom` or `dp_img_maxZoom`.

It's your project so I don't want to just do that.

18.03.2021 11:41:06 Vishesh Handa ***@***.***>:

**Comment by ModProg** [comment]
> This is so awesome. Let me know when you want me to merge it. I can do it now or after you feel it's done.

Ready to be merged

**Pull request merged**
