### PR TITLE
SVG Rendering and Image Theming

### PR DESCRIPTION
**Pull request by ModProg**
## Connection with issue(s)

Resolve issue #246 

## Testing and Review Notes
- SVGs should render correctly ([There are some things not working](https://github.com/dnfield/flutter_svg/issues))
- Theming:
  - By default SVGs with background and raster graphics should not be themed 
  - Overrides should work in both altText and Tooltip
  - Background detection works on checking if there is any path containing all 4 corners, this may result in false positives
  - You can choose which colors should be changed: `all`, `grays`, `black and white`

## Screenshots or Videos
Default-Settings:
grafik
White is adjusted to match Background:
grafik
All Colors are themed:
grafik
Brightness of Saturated Colors is not changed:
grafik

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers

### CODE REVIEW

**Comment by vHanda** [comment]
Hi. This is really amazing.

Sorry about the delay. After exploring different CLA options and finally speaking to a lawyer friend, it seems the most 
reliable route is old school signatures in a document. I'm in the process of preparing the document, I want to run it by a friend tomorrow. So hopefully this will be merged within this week.

**Comment by vHanda** [comment]
Hey.

The CLA is a mess. Since I live in Spain, Spanish law applies and I'm not sure if copying another project's CLA would just work. I've run it by friends, but they also don't know. I've finally emailed a lawyer from the FSFE. Let's see how this goes.

Till then, I've relicensed the files you touched to the Apache 2 license. I can merge these if you're also okay with licensing your code changes under Apache 2. If so, could you please add the Apache2 license header in the new files you have created?

Thanks for this awesome change, and the others. From now on I'll just keep relicensing all the files you touch, so your pull requests can be merged ASAP.

**Comment by ModProg** [comment]
> Hey.
> 
> The CLA is a mess. Since I live in Spain, Spanish law applies and I'm not sure if copying another project's CLA would just work. I've run it by friends, but they also don't know. I've finally emailed a lawyer from the FSFE. Let's see how this goes.
> 
> Till then, I've relicensed the files you touched to the Apache 2 license. I can merge these if you're also okay with licensing your code changes under Apache 2. If so, could you please add the Apache2 license header in the new files you have created?
> 
> Thanks for this awesome change, and the others. From now on I'll just keep relicensing all the files you touch, so your pull requests can be merged ASAP.

That's great, woul'd you rather merge this together with my other pull request when that is done?

And is `widgets/blend_mask.dart` licensed under MIT ok to use?

**Comment by vHanda** [comment]
MIT works.

I'm happy to merge this right now. Unless you prefer I wait. Your choice.

**Comment by ModProg** [comment]
> MIT works.
> 
> I'm happy to merge this right now. Unless you prefer I wait. Your choice.

I have an examen coming up, after that I will prepare everything for the merge.

**Comment by ModProg** [comment]
Should I just copy your header/add my name to it?

**Comment by vHanda** [comment]
Yes please. That would be the easiest.

**Comment by ModProg** [comment]
What about en.yaml and pubspec.yaml

**Comment by vHanda** [comment]
> What about en.yaml and pubspec.yaml

It's fine. The translations are under a different license anyway. And for the pubspec, at this point we might be being too picky. I presume you're not going to complain to Apple saying your possibly GPL licensed code of a few lines and I don't think they would take down the app for it.


The one case where I know they did is when that person had contributed thousands of lines. (VLC)

**Comment by ModProg** [comment]
Alright #406 should now be ready to be merged. 
Fingers crosse I did not introduce any bugs

**Pull request closed without merging**
