### PR TITLE
Add Japanese Localization

### PR DESCRIPTION
**Pull request by vrtmrz**
## Connection with issue(s)

Resolve issue #504 

As GitJournalApp says for me in twitter, I made Japanese locale resource and added localizations to app.
This is my first PR ever. If there're any mistakes, please feel free to tell me.

### CODE REVIEW

**Comment by vHanda** [comment]
This is great. Thank you.

When I saw the bug report, I got a bit scared since I read the word Kanji and I don't quite understand it. Sorry for not replying.

**Comment by vrtmrz** [comment]
Never mind, Thank you so much for merging!
I think I'd feel the same if I were you.
Asian letters are so complicated.. 
If you adding new resources, please notify me.

**Comment by vHanda** [comment]
> Never mind, Thank you so much for merging!
> I think I'd feel the same if I were you.
> Asian letters are so complicated..
> If you adding new resources, please notify me.

Hey. I've uploaded your translations over here - https://poeditor.com/projects/po_edit?id_language=76&per_page=20&id=369501

Could you please create a user? That way you'll be notified when new terms are added.

**Comment by vrtmrz** [comment]
Sure! I created an account as vrtmrz@gmail.com.

**Pull request merged**
